name: snatched
description: Food App.

version: 1.0.0+1

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  after_layout: ^1.0.7+2
  shared_preferences: ^0.5.7+3
  provider: ^4.1.3
  firebase_auth: ^0.16.1
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  firebase_analytics: ^5.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter



# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/foodie_image1.png
    - assets/images/foodie_image2.png
    - assets/images/foodie_image3.png

  fonts:
    - family: ProximaLight
      fonts:
        - asset: assets/fonts/Proxima_Nova_Light.otf
 
    - family:  CustomIcons
      fonts:
       - asset: assets/fonts/CustomIcons.ttf
